---
  - name: upgrade all packages RHEL
    dnf:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: update Debian
    apt:
      update_cache: yes
      upgrade: dist
      autoremove: yes
      autoclean: yes
    when: ansible_os_family == "Debian"

  #- name: update Alpine
  #  apk:
  #    update_cache: yes
  #    upgrade: yes
  #  when: ansible_distribution == "Alpine"

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file
    when: ansible_system == "Linux"

  - name: rebooting
    reboot:
      post_reboot_delay: 15
    when: ansible_system == "Linux" and reboot_required_file.stat.exists == true

  - name: Install all updates and reboot as many times as needed
    win_updates:
      category_names: '*'
      reboot: yes
    ignore_errors: true
    when: "'Windows' in group_names"