---
- name: Running playbook Linux
  hosts: localhost
  become: yes
  gather_facts: true
  roles:
    - ansible-setup
    - Hourly-Updates
    - packages-setup
    - users-setup
    - ssh-setup
    - auto-reboot

#- name: Running playbook Windows
#  hosts: Windows
#  gather_facts: true
#  roles:
#    - Hourly-Updates
#    - role: New-Server

#- name: External hosts setup
#  hosts: External
#  become: yes
#  gather_facts: true
#  vars:
