- name: Install Packages
  package:
    state: present
    name:
      - net-tools
      - curl
      - git
      - gpg

- name: required package for proxmox vms
  package:
    state: present
    name:
      - qemu-guest-agent
  when: ansible_virtualization_type == "kvm"
  

- name: Start and enable qemu-guest-agent
  service:
    name: qemu-guest-agent
    state: started
    enabled: yes
  when: ansible_virtualization_type == "kvm"