- name: Install Packages
  package:
    state: present
    name:
      - qemu-guest-agent
      - net-tools
      - curl
      - git
      - gpg
  when: ansible_virtualization_type == "kvm"

- name: Install Packages
  package:
    state: present
    name:
    - net-tools
    - curl
    - git
    - gpg
  when: '"lxc" in ansible_virtualization_type'

- name: Start and enable qemu-guest-agent
  service:
    name: qemu-guest-agent
    state: started
    enabled: yes
  when: ansible_virtualization_type == "kvm"