---
    # update system
    #create user
    - name: creating user Ubuntu
      ansible.builtin.user:
        name: delta
        groups: sudo
        append: yes
        password: $6$mysecretsalt$m.xhFiixz9E.g9MgEpJVzF/IHI/n9P4zqZyTWz2lh2VnOptxfVbylOU8.RgydDiyyscYk70FybQy9S579DGf0/
        state: present
        createhome: yes
        shell: /bin/bash
        update_password: on_create
      ignore_errors: true
      when: ansible_distribution == "Ubuntu"
    
    - name: creating user RHEL
      ansible.builtin.user:
        name: delta
        groups: wheel
        append: yes
        password: $6$mysecretsalt$m.xhFiixz9E.g9MgEpJVzF/IHI/n9P4zqZyTWz2lh2VnOptxfVbylOU8.RgydDiyyscYk70FybQy9S579DGf0/
        state: present
        createhome: yes
        shell: /bin/bash
        update_password: on_create
      ignore_errors: true
      when: ansible_distribution == "RedHat" or ansible_distribution == "Alpine"

    # ssh setup
    - name: adding certificate to ssh
      copy:
        dest: /etc/ssh/cert_ca.pub
        content: "{{certificate}}"

    - name: adding certificate to config
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "TrustedUserCAKeys /etc/ssh/cert_ca.pub"
        state: present
      register: ssh_cert
    
    - name: removing password auth
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "PasswordAuthentication no"
        state: present

    - name: restarting ssh
      service:
        name: sshd
        state: restarted
      when: ssh_cert.changed
    
    # installing packages
    - name: Install Packages
      package: 
        state: present
        name:
          - qemu-guest-agent
          - net-tools
          - curl
    
    #Rsyslog setup
#    - name: adding config for rsyslog collector Ubuntu
#      copy:
#        src: /home/ansible/builds/bcFayup4/0/markaplay/Ansible/roles/New-Server/files/rsyslog.conf
#        dest: /etc/rsyslog.d/50-default.conf
#        owner: root
#        group: root
#        mode: 0644
#        remote_src: no
#      register: rsyslog_output
#      when: ansible_distribution == "Ubuntu"

#    - name: adding config for rsyslog collector RHEL
#      copy:
#        src: /home/ansible/builds/bcFayup4/0/markaplay/Ansible/roles/New-Server/files/rsyslog.conf
#        dest: /etc/rsyslog.conf
#        owner: root
#        group: root
#        mode: 0644
#        remote_src: no
#      register: rsyslog_output
#      when: ansible_distribution == "RedHat" or ansible_distribution == "Alpine"

#    - name: restartting rsyslog
#      service:
#        name: rsyslog
#        state: restarted
#      when: rsyslog_output.changed

#    # Setup Timezone
#    - name: set timezone to America/Toronto
#      timezone:
#        name: America/Toronto
#      when: ansible_distribution != "Alpine"
