---
#Rsyslog setup
#    - name: adding config for rsyslog collector Ubuntu
#      copy:
#        src: /home/ansible/builds/bcFayup4/0/markaplay/Ansible/roles/New-Server/files/rsyslog.conf
#        dest: /etc/rsyslog.d/50-default.conf
#        owner: root
#        group: root
#        mode: 0644
#        remote_src: no
#      register: rsyslog_output
#      when: ansible_distribution == "Ubuntu"

#    - name: adding config for rsyslog collector RHEL
#      copy:
#        src: /home/ansible/builds/bcFayup4/0/markaplay/Ansible/roles/New-Server/files/rsyslog.conf
#        dest: /etc/rsyslog.conf
#        owner: root
#        group: root
#        mode: 0644
#        remote_src: no
#      register: rsyslog_output
#      when: ansible_distribution == "RedHat" or ansible_distribution == "Alpine"

#    - name: restartting rsyslog
#      service:
#        name: rsyslog
#        state: restarted
#      when: rsyslog_output.changed

#    # Setup Timezone
#    - name: set timezone to America/Toronto
#      timezone:
#        name: America/Toronto
#      when: ansible_distribution != "Alpine"
