---
- name: setting systemd service
  copy:
    src: files/ansible-update.service
    dest: /etc/systemd/system/ansible-update.service
    owner: root
    group: root
    mode: 0644
    remote_src: no

- name: setting systemd timer
  copy:
    src: files/ansible-update.timer
    dest: /etc/systemd/system/ansible-update.timer
    owner: root
    group: root
    mode: 0644
    remote_src: no

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: enable systemd timer
  systemd:
    name: ansible-update.timer
    enabled: yes
    state: started

- name: check if gpg is present
  stat:
    path: /usr/bin/gpg
  register: gpg_present

- name: Check if GPG key is already imported.
  ansible.builtin.command: /usr/bin/gpg --list-keys --keyid-format=long | grep 'ABE6828C0BC48D96'
  ignore_errors: true
  register: gpg_key
  when: gpg_present.stat.exists == true

- name: Copy github GPG key.
  ansible.builtin.copy:
    src: files/github.gpg
    dest: /tmp/github.gpg
    mode: '0644'
    force: true
  when: 
    - gpg_key.rc != 0
    - gpg_present.stat.exists == true

- name: Import github GPG key.
  ansible.builtin.command: /usr/bin/gpg --import=/tmp/github.gpg
  when: 
    - gpg_key.rc != 0
    - gpg_present.stat.exists == true

- name: Remove github GPG key.
  ansible.builtin.file:
    path: /tmp/github.gpg
    state: absent

