---
    - name: fetching the keys of telegraf repo
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present
      when: ansible_distribution_release == "focal"

    - name: adding the repository
      apt_repository:
        repo: deb https://repos.influxdata.com/{{ ansible_facts['distribution']|lower }} {{ ansible_facts['distribution_release'] }} stable
        state: present
      when: ansible_distribution_release == "focal"

    - name: updating the repository
      apt:
        update_cache: yes
      when: ansible_distribution_release == "focal"

    - name: installing telegraf
      package:
        name: telegraf
        state: latest
      register: install

    - name: configuring telegraf variables
      lineinfile:
        path: /etc/default/telegraf
        regexp: "^INFLUX_TOKEN=.*"
        line: INFLUX_TOKEN={{ INFLUX_TOKEN }}
        state: present
        create: yes

    - name: configuring telegraf service
      lineinfile:
        path: /lib/systemd/system/telegraf.service
        regexp: "^ExecStart=.*"
        line: ExecStart=/usr/bin/telegraf --config http://plintdb121.markaplay.net:8086/api/v2/telegrafs/0980b7f44cc17000
        state: present
      register: Service_ischanged

    - name: reloading daemon
      systemd:
        daemon_reload: yes
      when: Service_ischanged.changed

    - name: restarting telegraf service
      service:
        name: telegraf
        state: restarted
      when: Service_ischanged.changed or install.changed